_target_: src.models.cifar_module.CIFARLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.simple_cifar_net.SimpleCifarNet
  input_size: 32
  lin1_channel_size: 64
  lin2_channel_size: 128
  lin3_channel_size: 256
  output_size: 10
